### ISSUE TITLE
COINS: dynamically generating contextualized inference rules for narrative story completion

### ISSUE THREAD

**Issue by debjitpaul** [wyu97/KENLG-Reading#1]
Hey, 

Firstly, it is a great Github page! I really like your collection. We have a ACL 2021 paper on the topic of Knowledge enhanced story generation. It might be interesting for you. 

Paper name : COINS: dynamically generating contextualized inference rules for narrative story completion 
Github: https://github.com/Heidelberg-NLP/COINS
Link: https://aclanthology.org/volumes/2021.acl-long/

Best regards,
Debjit

**Comment by wyu97** [comment]
Hi Debjit, 

Thanks for your support! This work is interesting, and I have added it to our repo! 

And if you find our paper and repo useful, you may consider to cite our paper in your following works. 

Best regards,
Wenhao
